name: Build and Deploy PDCurses WASM

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: 'latest'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev fonts-dejavu
        
    - name: Clone PDCurses
      run: |
        git clone https://github.com/wmcbrine/PDCurses.git pdcurses
        
    - name: Set up assets directory
      run: |
        mkdir -p assets
        cp /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf assets/ || echo "Default font not found, using system font"
        if [ ! -f assets/DejaVuSansMono.ttf ]; then
          find /usr/share/fonts -name "*.ttf" | head -1 | xargs -I{} cp {} assets/DejaVuSansMono.ttf
        fi
        
    - name: Fix main.c
      run: |
        sed -i '/^\/\//s/^\/\///' main.c
        
    - name: Build WASM
      run: |
        emcc -O2 -Wall -Ipdcurses main.c $(find pdcurses/sdl2 -name "*.c") $(find pdcurses/pdcurses -name "*.c") \
        -o hello_pdcurses.html \
        -s WASM=1 -s USE_SDL=2 -s USE_SDL_TTF=2 -s ALLOW_MEMORY_GROWTH=1 \
        -s EXPORTED_RUNTIME_METHODS='["cwrap"]' \
        --preload-file assets \
        -s ASYNCIFY=1 \
        -s ASSERTIONS=1 \
        -s SAFE_HEAP=1 \
        -s ERROR_ON_UNDEFINED_SYMBOLS=0 \
        -s EXPORTED_FUNCTIONS='["_main", "_malloc"]' \
        --shell-file shell.html
        
    - name: Create dummy.c if needed
      run: |
        echo "/* Empty file to satisfy emscripten linker */" > dummies.c
        
    - name: Setup Pages
      if: github.event_name != 'pull_request'
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-pages-artifact@v2
      with:
        path: '.'
        
    - name: Deploy to GitHub Pages
      if: github.event_name != 'pull_request'
      id: deployment
      uses: actions/deploy-pages@v2
      
permissions:
  contents: read
  pages: write
  id-token: write